apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-demo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/mikeebraga/ArgoCD_Vs_FluxCD
  ref:
    branch: main
