name: Build and Push Image

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/mikeebraga/gitops-demo

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag version
        id: meta
        run: |
          TAG=${GITHUB_REF_NAME}
          echo "VERSION=${TAG}" >> $GITHUB_OUTPUT
          # folder is v1 or v2 — take only the major part (v1.0.0 → v1)
          echo "FOLDER=v$(echo ${TAG} | cut -d. -f1 | tr -d 'v')" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./sample-app/src/${{ steps.meta.outputs.FOLDER }}
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ steps.meta.outputs.VERSION }}
            ${{ env.IMAGE }}:latest
